version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "component: CI"
    groups:
      actions:
        patterns:
          - "*"
