# Process changelog_in.md to create changelog.md with correct links for PRs and github usernames.

import re

input_filename = "changelog.md.in"
output_filename = "changelog.md"
repo = r"https://github.com/contourpy/contourpy"


def convert_line(line: str) -> str:
    line = re.sub(r"#(\d+)", r"[#\1](" + repo + r"/pull/\1)", line)  # PR of form #123
    line = re.sub(r"@{1}([\w\-]+)", r"[@\1](https://github.com/\1)", line)  # Username of form @name
    return line


def process_changelog() -> None:
    with open(input_filename) as input:
        with open(output_filename, "w") as output:
            output.write("<!-- This file is autogenerated, do not edit -->\n\n")
            output.write("(changelog)=\n\n")

            for line in input.readlines():
                line = convert_line(line)
                output.write(line)


if __name__ == "__main__":
    process_changelog()
