name: Test (cibuildwheel)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  cibuildwheel_test:
    name: Test (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: pyodide
            os: ubuntu-24.04
            arch: auto
            platform: pyodide
          - name: iOS-arm64
            os: macos-latest
            arch: arm64_iphonesimulator
            platform: ios
          - name: iOS-x86_64
            os: macos-15-intel
            arch: x86_64_iphonesimulator
            platform: ios

    steps:
      - name: Checkout source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: 3.13

      - name: Build and test pyodide wheels
        uses: pypa/cibuildwheel@294735312765b09d24a2fbec22660ce817587d55 # v4.1.0
        env:
          CIBW_PLATFORM: ${{ matrix.platform }}
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_TEST_REQUIRES: pytest pytest-rerunfailures<16
          CIBW_TEST_SOURCES: tests
          CIBW_TEST_COMMAND: python -m pytest -v ./tests --ignore=./tests/test_codebase.py -k "not image and not big"

      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ matrix.name }}-wheels
          path: ./wheelhouse/*.whl
